name: hello worlds

on:
  push:
  workflow_call: # 他のworkflow から呼びだされるのを許可

jobs:
  first_hello:
    uses: hrk-m/worker-github-actions-workflow/.github/workflows/hello-world.yml@main

  second_hello:
    runs-on: ubuntu-latest
    needs: first_hello
    steps:
      - name: Run a one-line script
        run: echo Hello, world too!
